#!/bin/sh
DOWNLOAD_DIR="$HOME/Documents/torrent/manga/"
QUERY=$(printf "%s" "$*" | sed 's/ /+/g')
LINK="https://nyaa.si/?f=0&c=3_3&q=$QUERY&s=seeders&o=desc"
TORRENT_LINK=$(curl -s "$LINK" -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0' \
    | pup 'body tr.default td.text-center a' \
    | grep -Eo "\/download\/[a-zA-Z0-9?%-' '=.+;-]*" \
    | head -n 1)
TORRENT_NAME_NUM=$(echo $TORRENT_LINK | grep -Eo "[0-9]*") && TORRENT_FILE_TYPE=".torrent" && TORRENT_NAME=$TORRENT_NAME_NUM$TORRENT_FILE_TYPE
DOWNLOAD=$(curl -Lo "$DOWNLOAD_DIR$TORRENT_NAME" https://nyaa.si$TORRENT_LINK)
webtorrent download $DOWNLOAD_DIR$TORRENT_NAME -o $DOWNLOAD_DIR
